[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

#[cursor]
#blinking = "on"

[font]
size = 9.5

[font.bold]
family = "monospace"
style = "Bold"

[font.normal]
family = "monospace"
style = "Normal"

[shell]
program = "/bin/bash"

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.9
title = "Terminal"

[window.padding]
x = 8
y = 8
